---
output: github_document
params:
  issue_url: NULL
  date: NULL
---

## Confirm your organisation membership

We are reviewing membership of the [ScotGovAnalysis GitHub organisation](https://github.com/ScotGovAnalysis). 

It is important for us to do this periodically to ensure only appropriate users have access to our repositories. For example, people may keep the same GitHub account as they move jobs but it might not be appropriate for them to remain a member of the Scottish Government organisation.

> [!TIP]
> **You will need to [log in and view this message on GitHub](`r params$issue_url`) to respond.**

### If you want to continue being a member of ScotGovAnalysis:

Please review the following requirements and tick each box to confirm:

- [ ] I am a current Scottish Government employee.
- [ ] I have reviewed and agree to adhere to the [GitHub User Responsibilities](https://scotsconnect.sharepoint.com/sites/StatisticsGroup-Org-SG/SitePages/GitHub-User-Responsibilities.aspx).
- [ ] I would like to continue my membership of the [ScotGovAnalysis organisation](https://github.com/ScotGovAnalysis).

### If you want to stop being a member of ScotGovAnalysis:

If you do not respond to this message by **`r params$date`**, we will assume you no longer need access and remove you from the organisation. You will be able to request to re-join if your circumstances change in the future.

### Help

If you have any questions or need any help, please [get in touch with Alice Hannah](mailto:alice.hannah@gov.scot?subject=ScotGovAnalysis%20Membership%20Review).

Thank you for your support and cooperation.
